version: '3.1'

services:
  backend:
    build:
      context: . # Root directory
      dockerfile: Dockerfile.be
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      APP_URL: ${APP_URL}
      AUTH_SESSION_NAME: ${AUTH_SESSION_NAME}
      AUTH_SESSION_SECRET: ${AUTH_SESSION_SECRET}
      AUTH_SESSION_RESAVE: ${AUTH_SESSION_RESAVE}
      AUTH_SESSION_SAVE_UNINITIALIZED: ${AUTH_SESSION_SAVE_UNINITIALIZED}
      RPC_API_KEY: ${RPC_API_KEY}

  frontend:
    build:
      context: . # Root directory
      dockerfile: Dockerfile.fe
    ports:
      - '3000:3000' # Assuming standard Next.js port as UI_PORT isn't defined in your env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_PROJECT_ID: ${NEXT_PUBLIC_PROJECT_ID}
    depends_on:
      - backend